name: web_socket_support_platform_interface
description: A common platform interface for the web_socket_support plugin.
homepage: https://github.com/sharpbitstudio/flutter-websocket-support-platform-interface
version: 0.3.1

environment:
  sdk: ">=2.16.0 <4.0.0"
  flutter: ">=2.10.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.11.0
  meta: ^1.15.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  flutter_lints: ^5.0.0
