name: web_socket_support_platform_interface
description: A common platform interface for the web_socket_support plugin.
homepage: https://github.com/sharpbitstudio/flutter-websocket-support-platform-interface
version: 0.2.2

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  async: ^2.8.1
  meta: ^1.3.0
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.0.16
  flutter_lints: ^1.0.4
