name: web_socket_support_platform_interface

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the develop branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Job configuration for the web_socket_support_platform_interface (Platform Interface Package)
  platform_interface_build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    timeout-minutes: 20
    env:
      CODECOV_TOKEN: 8158d78c-f445-4ab2-990f-5c3663b6dea7

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Make sure the stable version of Flutter is available
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable' # or: 'beta' or 'dev'

      # Download all Flutter packages the WebsocketSupport depends on
      - name: Download dependencies
        run: flutter pub get

      # Run Flutter Format to ensure formatting is valid
      - name: Run Flutter Format
        run: flutter format --set-exit-if-changed lib
      
      # Run Flutter Analyzer
      - name: Run Flutter Analyzer
        run: flutter analyze
      
      # Run all unit-tests with code coverage
      - name: Run unit tests
        run: flutter test --coverage

      # Upload code coverage information
      - uses: codecov/codecov-action@v2
        with:
          file: ./coverage/lcov.info # optional
          name: WebSocketSupport (Platform Interface Package) # optional
          fail_ci_if_error: true
          verbose: true
